### PR TITLE
Add wheel support for aarch64

### PR DESCRIPTION
**Pull request by odidev**
Added wheel support for aarch64.
Related to #7 .

### CODE REVIEW

**Comment by tbbharaj** [comment]
Following up on this PR, looks like there is merge conflict here. It will be beneficial to have aarch64 wheels available on PyPI repository rather than building it from source code.

**Comment by sgillies** [comment]
I'm on vacation. Will address this next week.

**Comment by tbbharaj** [comment]
> I'm on vacation. Will address this next week.

Sure, Thanks!

**Comment by sgillies** [comment]
@tbbharaj this PR doesn't work. I'm going to close it and start from scratch following the example in the pillow-wheels repo.

**Comment by tbbharaj** [comment]
> @tbbharaj this PR doesn't work. I'm going to close it and start from scratch following the example in the pillow-wheels repo.

@sgillies Thank you for the update! Do you have estimated timeline you plan to add the aarch64 wheels support?

**Pull request closed without merging**
